version: "3.7"
services:
  base-web-8861-mysql:
    image: mysql:5.7
    container_name: base-web-8861-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cms
    ports:
      - "3308:3306"
  base-web-8861-mysql-admin:
    image: adminer
    container_name: base-web-8861-mysql-admin
    ports:
      - "8080:8080"
    depends_on:
      - base-web-8861-mysql
