version: "3.7"
services:
  {gcp_project_id}-mysql:
    image: mysql:5.7
    container_name: {gcp_project_id}-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cms
    ports:
      - "3308:3306"
  {gcp_project_id}-mysql-admin:
    image: adminer
    container_name: {gcp_project_id}-mysql-admin
    ports:
      - "8080:8080"
    depends_on:
      - {gcp_project_id}-mysql
